name: Containers

permissions: write-all

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-bazel-ci

on:
  push:
    paths:
      - .devcontainer/Dockerfile
    branches:
      - main
  workflow_dispatch:

jobs:
  push-bazel-container:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        bazel_version: ["6.4.0", "7.5.0"]
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Login to GCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Echo
      run: |
        echo "USER: ${{ github.actor }}"
        echo "REPOSITORY: ${{ github.repository }}"
        echo "BAZEL_VERSION: ${{ matrix.bazel_version }}"
        echo "TAGS: ${{ steps.meta.outputs.tags }}"
        echo "LABELS: ${{ steps.meta.outputs.labels }}"
    - name: Image - Bazel
      uses: docker/build-push-action@v5
      with:
        file: ./.devcontainer/Dockerfile
        push: true
        build-args: |
            BAZEL_VERSION=${{ matrix.bazel_version }}
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:bazel${{ matrix.bazel_version }}
        labels: ${{ steps.meta.outputs.labels }}
